import React from 'react';
import { Link } from 'react-router-dom';
import './HeroSection.css';

export default function HeroSection() {
    return (
        <section className="hero">
            <h1>Your day in the life <em className="autogenerated-text">Autogenerated</em></h1>
            <button className="cta">Get early access</button>
            <div className="privacy-notice">Please read our <Link to="/privacy-policy" className="privacy-link">privacy policy</Link></div>
        </section>
    );
} 