import React from 'react';
import './HeroSection.css';

export default function HeroSection() {
    return (
        <section className="hero">
            <h1>Your day in the life <em className="autogenerated-text">Autogenerated</em></h1>
            <p>Find My and Spotify had a baby</p>
            <button className="cta">Get early access</button>
        </section>
    );
} 